// src/components/PasswordLegend.tsx
import React from 'react';
import { Typography } from '@mui/material';

interface Props {
  password: string;
}

const PasswordLegend: React.FC<Props> = ({ password }) => {
  const isMinLengthMet = password.length >= 8;
  const isSpecialCharMet = /[!@#$%^&*(),.?":{}|<>]/.test(password);
  const isUpperCaseMet = /[A-Z]/.test(password);
  const isLowerCaseMet = /[a-z]/.test(password);

  return (
    <div className="text-sm text-gray-600 mt-2">
      <Typography component="ul" sx={{ pl: 2, listStyleType: 'disc' }}>
        {!isMinLengthMet && <li>min 8 characters</li>}
        {!isSpecialCharMet && <li>a special character</li>}
        {!isUpperCaseMet && <li>an uppercase letter</li>}
        {!isLowerCaseMet && <li>a lowercase letter</li>}
      </Typography>
    </div>
  );
};

export default PasswordLegend;

// src/components/password-legend/password-legend.component.ts
import { Component, Input } from '@angular/core';
import { NgIf } from '@angular/common';
import { FormGroup } from '@angular/forms';
import { animate, style, transition, trigger } from '@angular/animations';

@Component({
  selector: 'app-password-legend',
  imports: [NgIf],
  templateUrl: './password-legend.component.html',
  styleUrl: './password-legend.component.scss',
  animations: [
    trigger('fade', [
      transition(':leave', [animate('0.5s ease-out', style({ opacity: 0 }))]),
    ]),
  ],
})
export class PasswordLegendComponent {
  @Input() form!: FormGroup;

  isMinLengthMet(): boolean {
    const password = this.form.get('password')?.value;
    return password && password.length >= 8;
  }

  isSpecialCharMet(): boolean {
    const password = this.form.get('password')?.value;
    return password && /[!@#$%^&*(),.?":{}|<>]/.test(password);
  }

  isUpperCaseMet(): boolean {
    const password = this.form.get('password')?.value;
    return password && /[A-Z]/.test(password);
  }

  isLowerCaseMet(): boolean {
    const password = this.form.get('password')?.value;
    return password && /[a-z]/.test(password);
  }
}

<div>
  <ul class="list-disc pl-5">
    <li *ngIf="!isMinLengthMet()" @fade>min 8 characters</li>
    <li *ngIf="!isSpecialCharMet()" @fade>a special character</li>
    <li *ngIf="!isUpperCaseMet()" @fade>an uppercase letter</li>
    <li *ngIf="!isLowerCaseMet()" @fade>a lowercase letter</li>
  </ul>
</div>
